#secrets.toml

# Ersetzen Sie diese Werte mit Ihren Daten aus dem Supabase Dashboard
SUPABASE_URL = "https://ixlwcourvdblienxfexn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bHdjb3VydmRibGllbnhmZXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjY3MzEsImV4cCI6MjA2OTc0MjczMX0.B4BYlhw1azNCankb6AXGrKGKBYaC4MBd3V0tzRjIqts"